### ISSUE TITLE
{"errno":34,"code":"ENOENT","path":"C:\\Users\\Antonio\\PREV\\resources\\jobs\\jobs.js","INVALID_EXPRESSION_ERR":51,"TYPE_ERR":52}

### ISSUE THREAD

**Issue by ramstein74** [yannisgu/dpd-jobs#1]
hello i have the above error
what is it?

if i go to code window and execute a simple console.log('test')  i can see it in the console.
as soon as i put a cron definition as suggested "*/5 \* \* \* *"  and come back to code to execute i have the above error.

can you post a simple example on how to use cron?
thank you

**Comment by PJCzx** [comment]
Hello, I have the same problem:

1. Created a new collection "jobs" of type Jobs
2. Entered "console.log('Hello world');"
3. Clicked save
4. Click Run 

Dpd  crashes with this console output: 

`dpd > RangeError: Maximum call stack size exceeded - when initializing: Jobs
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/local/lib/node_modules/deployd/lib/script.js:316:31)
    at /usr/local/lib/node_modules/deployd/lib/script.js:321:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/local/lib/node_modules/deployd/lib/script.js:316:31)
    at /usr/local/lib/node_modules/deployd/lib/script.js:321:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/local/lib/node_modules/deployd/lib/script.js:316:31)
    at /usr/local/lib/node_modules/deployd/lib/script.js:321:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/local/lib/node_modules/deployd/lib/script.js:316:31)
    at /usr/local/lib/node_modules/deployd/lib/script.js:321:7
    at Array.forEach (native)
    at wrapAsyncFunctions (/usr/local/lib/node_modules/deployd/lib/script.js:316:31)
    at /usr/local/lib/node_modules/deployd/lib/script.js:321:7
    at Array.forEach (native)
bye`

I restarted the dpd instance and went to the run logs, found this:

Date | Message | Source
------------ | ------------- | ------------
2015-09-23 11:40:00 | {"errno":-2,"code":"ENOENT","path":"resources/jobs/jobs.js"} | system

The file resources/jobs/jobs.js exist and contains the code.

Any idea ?

Thank you :)
