### ISSUE TITLE
Error loading module node_modules/dpd-jobs 

### ISSUE THREAD

**Issue by ramstein74** [yannisgu/dpd-jobs#4]
My system is a ubuntu 12.04 server

hello inside my app i did 
npm install dpd-jobs 
and after starting dpd -p 3000 & i get an error on console

Error loading module node_modules/dpd-jobs
Error: Cannot find module 'deployd/lib/resource'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/deployd/app1/node_modules/dpd-jobs/index.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
root@CIRES:~/deployd/app1#

this is my ls of dpd-jobs afer instalation

root@CIRES:~/deployd/app1# ls node_modules/dpd-jobs/ -la
total 44
drwxr-xr-x 4 root root 4096 May 28 05:36 .
drwxr-xr-x 3 root root 4096 May 28 05:36 ..
drwxr-xr-x 3 root root 4096 May 28 05:36 dashboard
-rw-r--r-- 1 root root 1041 Jan 11 18:42 Gruntfile.js
-rw-r--r-- 1 root root 5693 Jan 11 18:42 index.js
drwxr-xr-x 4 root root 4096 May 28 05:36 node_modules
-rw-r--r-- 1 root root   94 Jan 11 18:42 .npmignore
-rw-r--r-- 1 root root 1891 May 28 05:36 package.json
-rw-r--r-- 1 root root  950 Jan 11 18:42 README.md
-rw-r--r-- 1 root root  307 Jan 11 18:42 .travis.yml

regards
António

**Comment by yannisgu** [comment]
Solution provided by @lovellfelix
