### ISSUE TITLE
node-schedule Update

### ISSUE THREAD

**Issue by hugsbrugs** [yannisgu/dpd-jobs#8]
In your index.js I had to change : 

```javascript
this.scheduledJob = schedule.scheduleJob(schedule.RecurrenceRule.fromCronString(cron), function(){
```
by : 
```javascript
this.scheduledJob = schedule.scheduleJob(cron, function(){
```
to get rid of :
 
```javascript
TypeError: Object function RecurrenceRule(year, month, date, dayOfWeek, hour, minute, second){
  this.recurs = true;
  
  this.year = (year == null) ? null : year;
  this.month = (month == null) ? null : month;
  this.date = (date == null) ? null : date;
  this.dayOfWeek = (dayOfWeek == null) ? null : dayOfWeek;
  this.hour = (hour == null) ? null : hour;
  this.minute = (minute == null) ? null : minute;
  this.second = (second == null) ? 0 : second;
} has no method 'fromCronString' - when initializing: Jobs
    at Jobs.initCron (/var/www/duplicates/node_modules/dpd-jobs/index.js:43:78)
    at new Jobs (/var/www/duplicates/node_modules/dpd-jobs/index.js:13:10)
    at /var/www/duplicates/node_modules/deployd/lib/config-loader.js:120:24
    at process._tickDomainCallback (node.js:463:13)
```

It seems, the node-schedule package no longer has **fromCronString** method.

I've never made a Pull Request, I can try if you want your module to be still working !

**Comment by yannisgu** [comment]
Yes, pull-request pleasae :)
